packages:
    - "projects/vanilla-web-server/**"
    - "projects/vanilla-http-caching/**"
    - "projects/express-web-server/**"
    - "projects/graphql-express-yoga/**"
    - "projects/websockets-socketio/**"
    - "projects/trpc-web-server/**"
    - "projects/redis-express-server/**"
    - "projects/sqlite-basic/**"
    - "projects/auth-vanilla/**"
    - "projects/server-side-sessions/**"
    - "projects/auth-oauth-passport/**"
    - "projects/auth-passport-cookie-session/**"
