packages:
    - "projects/vanilla-web-server/**"
    - "projects/vanilla-http-caching/**"
    - "projects/express-web-server/**"
    - "projects/graphql-express-yoga/**"
    - "projects/websockets-socketio/**"
    - "projects/trpc-web-server/**"
    - "projects/redis-express-server/**"
